server:
  port: 8080
spring:
  application:
    name: Medical-backend
  config:
    import: optional:file:/Users/huynhthach/Documents/ChatBotMedical/.env
  datasource:
    url: jdbc:postgresql://{DB_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # hoặc validate / create / create-drop tùy nhu cầu
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true